name: Build
on:
  push:
    branches:
      - "master"
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup NodeJS 🟢
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"
      - name: Install npm packages
        run: yarn install
      - name: Start Building
        run: yarn build
